

<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">
	<link rel="icon" href="favicon.ico">

	<title>BlastMe Admin Page | Dashboard</title>

	<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>	
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />

	<link href="css/app.css" rel="stylesheet">
</head>

<body>
	
	<div class="splash active">
		<div class="splash-icon"></div>
	</div>

	<nav class="navbar navbar-expand navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="/index.php">
				<img src="assets/test.png" alt="NeuAPIX" class="img-fluid" width="200" height="200"/><br>
      		</a>

			<div class="navbar-collapse collapse">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown ml-lg-2">
						<a class="nav-link dropdown-toggle" href="#" id="userDropdown" data-toggle="dropdown">
							<span class="d-none d-lg-inline-block">User</span>
							<span class="d-lg-none"><i class="align-middle fas fa-cog"></i></span>
            			</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
							<a class="dropdown-item" href="index.php"><i class="align-middle mr-1 fas fa-fw fa-arrow-alt-circle-right"></i> Sign out</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="header">
		<div class="container">
			<div class="media text-white">
				<div class="media-body">
					<span class=" font-weight-normal">(JUDUL)</span>
				</div>
			</div>
		</div>
	</div>


	<main class="content">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-4 col-lg-3 col-xl-2">
    <a class="card d-block d-md-none mt-4" data-toggle="collapse" data-target="#sidebar">
        <div class="card-header">
            <h5 class="card-title mb-0">Menu</h5>
        </div>
    </a>

    <nav id="sidebar" class="collapse collapse-disabled-md sidebar sidebar-sticky">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Transaction</h5>
            </div>
            <div class="sidebar-content">
                <a href="#" class="sidebar-item">
                    <i class="align-middle mr-1 fas fa-fw fa-home"></i> <span class="align-middle">Dashboard</span>
                </a>
                <a class="sidebar-item" href="#transaction" data-toggle="collapse">
                    <i class="align-middle mr-1 fas fa-fw fa-desktop"></i> <span class="align-middle">Transaction</span>
                </a>
                <div class="sidebar-dropdown collapse" id="transaction" data-parent="#sidebar">
                    <a class="sidebar-item" href="./page/SMSTransactionReport.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c" >Transaction Report</a>
                </div>
                <div class="sidebar-dropdown collapse" id="transaction" data-parent="#sidebar">
                    <a class="sidebar-item" href="./page/CSVTransactionReports.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c" >Generated CSV Report</a>
                </div>
            </div>
        </div>

        
        
        
        	<div class="card">		<div class="card-header">			<h5 class="card-title mb-0">Sending</h5>		</div>		<div class="sidebar-content">			<a class="sidebar-item" href="#sendingsms" data-toggle="collapse">			<i class="align-middle mr-1 fas fa-fw fa-desktop"></i> <span class="align-middle">Sending SMS</span>			</a>			<div class="sidebar-dropdown collapse" id="sendingsms" data-parent="#sidebar">				<a class="sidebar-item" href="./page/AutoGeneratedANumberSMS.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c">Auto Generated A Number</a>			</div>		</div>	</div>

        
        
        
    </nav>
</div>
				
				<div class="col-12 col-md-8 col-lg-9 col-xl-10 pl-lg-4">

					<div class="row">
						<div class="col-6 col-xl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-3">
									<div class="row">
										<div class="col-12 col-sm-4 align-self-center text-center text-sm-left">
											<div class="icon icon-primary">
												<i class="align-middle" data-feather="trending-up"></i>
											</div>
										</div>
										<div class="col-12 col-sm-8 align-self-center text-center text-sm-right">
											<p class="text-muted mb-1">Traffic Today</p>
											<h2><i class="text-primary ion ion-ios-chatboxes"></i> 0</h2>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-6 col-xl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-3">
									<div class="row">
										<div class="col-12 col-sm-4 align-self-center text-center text-sm-left">
											<div class="icon icon-danger">
												<i class="align-middle" data-feather="shopping-cart"></i>
											</div>
										</div>
										<div class="col-12 col-sm-8 align-self-center text-center text-sm-right">
											<p class="text-muted mb-1">Usage Today</p>
											<h4><i class="text-danger ion ion-ios-chatboxes"></i> SMS 0.00000</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-6 col-xl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-3">
									<div class="row">
										<div class="col-12 col-sm-4 align-self-center text-center text-sm-left">
											<div class="icon icon-success">
												<i class="align-middle" data-feather="target"></i>
											</div>
										</div>
										<div class="col-12 col-sm-8 align-self-center text-center text-sm-right">
											<p class="text-muted mb-1">Success Rate</p>
											<h2><i class="text-primary ion ion-ios-chatboxes"></i> 0.00%</h2>
										</div>
									</div>
								</div>
							</div>
						</div>
						<div class="col-6 col-xl-3 d-flex">
							<div class="card flex-fill">
								<div class="card-body py-3">
									<div class="row">
										<div class="col-12 col-sm-4 align-self-center text-center text-sm-left">
											<div class="icon icon-warning">
												<i class="align-middle" data-feather="credit-card"></i>
											</div>
										</div>
										<div class="col-12 col-sm-8 align-self-center text-center text-sm-right">
											<p class="text-muted mb-1">Balance</p>
											<h4><i class="text-danger"></i>SMS 0.00000</h4>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-12 col-lg-12">
							<div class="card">
								<div class="card-header">
									<h5 class="card-title">Success Rate</h5>
									<h6 class="card-subtitle text-muted">Success rate for sms delivery at certain date period.</h6>
								</div>
								<div class="card-body text-center">
									<form>
										<div class="form-group">
											<div class="row">
												<label class="control-label col-sm-4">Transaction Date Time</label>
												<div class="col-sm-8">
													<input class="form-control" type="text" id="trxdate" name="trxdate" />
												</div>
											</div>
										</div>

										<div class="form-group">
											<div class="row">
												<div class="col-sm-12" align="right">
													<button class="btn btn-primary" id="btnViewPieChart" name="btnViewPieChart">View Pie Chart</button>&nbsp;
												</div>
											</div>
										</div>
									</form>

									<div class="chart">	
										<div id="apexcharts-pie" style="max-width: 440px;margin:auto;"></div>
									</div>
									
									<div class="row">
										<div class="col-12 col-lg-12">
											<label id = "labelRate">Delivered: 0 traffics, Undelivered: 0 traffics</label>
										</div>						
									</div>

									<script>	
										document.addEventListener("DOMContentLoaded", function(event) {
											var options = {
												chart: {
													id: "chartku",
													height: 350,
													type: "donut",
												},			
												dataLabels: {
													enabled: true
												},
												series: [0, 0],
												labels: ["DELIVERED", "UNDELIVERED"],
												legend: { 
													horizontalAlign: 'left',
													position: 'right', 
													offsetY: 0,
													height: 230
												},
												dataLabels: {
													enabled: true,
													formatter: function (val) {
													  return val.toFixed(3) + "%"
													}
												},
												tooltip: {
												  y: {
													formatter: function(value) {
													  return (parseFloat(value) * 100).toFixed(3) + "%";
													}
												  }
												}
											}

											var chart = new ApexCharts(
												document.querySelector("#apexcharts-pie"), options);		
	
											chart.render();	
										});
									</script>	
									
								</div>
							</div>
						</div>					
					</div>
					
					<div class="row">
						<div class="col-12 col-lg-12 d-flex">
							<div class="card flex-fill w-100">
								<div class="card-header">
									<h5 class="card-title mb-0">Today SMS Traffic</h5>
								</div>
								<div class="card-body">
									<div class="chart chart-lg mt-2">
										<canvas id="onedaysmstrafficgraph"></canvas>
									</div>
								</div>
							</div>

							<script>
								document.addEventListener("DOMContentLoaded", function(event) {
									// Line chart
									new Chart(document.getElementById("onedaysmstrafficgraph"), {
										type: 'line',
										data: {
											labels: ["2022-02-08 20:00:00", "2022-02-08 21:00:00", "2022-02-08 22:00:00", "2022-02-08 23:00:00", "2022-02-09 00:00:00", "2022-02-09 01:00:00", "2022-02-09 02:00:00", "2022-02-09 03:00:00", "2022-02-09 04:00:00", "2022-02-09 05:00:00", "2022-02-09 06:00:00", "2022-02-09 07:00:00", "2022-02-09 08:00:00", "2022-02-09 09:00:00", "2022-02-09 10:00:00", "2022-02-09 11:00:00", "2022-02-09 12:00:00", "2022-02-09 13:00:00", "2022-02-09 14:00:00", "2022-02-09 15:00:00", "2022-02-09 16:00:00", "2022-02-09 17:00:00", "2022-02-09 18:00:00", "2022-02-09 19:00:00", "2022-02-09 20:00:00"],											datasets: [{
												label: "Total Traffic",
												fill: true,
												backgroundColor: "rgba(65, 212, 146, 0.15)",
												borderColor: "#41D492",
												data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],											}, {label: "Success Traffic",

												fill: true,

												backgroundColor: "rgba(241, 169, 160, 0.5)",

												borderColor: "rgba(240, 52, 52, 1)",

												borderDash: [2, 2],

												data: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ],											}
											]
										},
										options: {
											maintainAspectRatio: false,
											legend: {
												display: false
											},
											tooltips: {
												intersect: false
											},
											hover: {
												intersect: true
											},
											plugins: {
												filler: {
													propagate: false
												}
											},
											elements: {
												line: {
													tension: 0
												}
											},
											scales: {
												xAxes: [{
													reverse: true,
													gridLines: {
														color: "rgba(0,0,0,0.0)"
													}
												}],
												yAxes: [{
													ticks: {
														stepSize: 0					
													},
													display: true,
													borderDash: [5, 5],
													gridLines: {
														color: "rgba(0,0,0,0)",
														fontColor: "#fff"
													}
												}]
											}
										}
									});
								});
							</script>
						</div>
					</div>					
				</div>
			</div>
		</div>
	</main>

	<script>
		
		
		$(function() {
  			$('input[name="trxdate"]').daterangepicker({
    			opens: 'left'
  			}, function(start, end, label) {
    			//console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  			});
		});	
		
		
		$("#btnViewPieChart").on('click', function(e) {
			var trxDateRange = $('#trxdate').val();
			
			e.preventDefault();
			
			$.post('dashboard_pie.php', { rangeDate: trxDateRange, jck: '1c4467b8308a55dc1dce7ce9e1e3df82f833321c' }, function(data){
				console.log('Data: ' + data);
				
				if(data!=null){
					if(data.startsWith('rld')){
						window.parent.location.reload();
					} else {
						console.log('Data clean: ' + data);
						var jsonRate = JSON.parse(data);
						
						ApexCharts.exec('chartku', 'updateSeries', [jsonRate.success, jsonRate.failed], true);
						
						$('#labelRate').text('Delivered: ' + jsonRate.successTraffic + ' traffics, Undelivered: ' + jsonRate.failedTraffic + ' traffics');
					}
				} else {
					alert('Failed to load data.');
					window.parent.location.reload();
				};
			}).fail(function(xhr) {
				//console.log(xhr.status);
				window.parent.location.reload();
			});
		})
	</script>

		<footer class="footer">
		<div class="container">
			<hr />
			<div class="text-muted">
				<div class="row text-center justify-content-center align-self-center align-items-end">
						Provided  By &nbsp;<a href="https://www.telin.net/neuapix"><img src="assets/test.png" alt="NeuAPIX" class="img-fluid" width="100" height="40"/></a>						
				</div>
			</div>
		</div>
	</footer>
	<script src="js/app.js"></script>
	
	<script>
		$('#btnViewPieChart').trigger('click');
	</script>

	<svg width="0" height="0" style="position:absolute">
    <defs>
      <symbol viewBox="0 0 512 512" id="ion-ios-pulse-strong"><path d="M448 273.001c-21.27 0-39.296 13.999-45.596 32.999h-38.857l-28.361-85.417a15.999 15.999 0 0 0-15.183-10.956c-.112 0-.224 0-.335.004a15.997 15.997 0 0 0-15.049 11.588l-44.484 155.262-52.353-314.108C206.535 54.893 200.333 48 192 48s-13.693 5.776-15.525 13.135L115.496 306H16v31.999h112c7.348 0 13.75-5.003 15.525-12.134l45.368-182.177 51.324 307.94c1.229 7.377 7.397 11.92 14.864 12.344.308.018.614.028.919.028 7.097 0 13.406-3.701 15.381-10.594l49.744-173.617 15.689 47.252A16.001 16.001 0 0 0 352 337.999h51.108C409.973 355.999 427.477 369 448 369c26.511 0 48-22.492 48-49 0-26.509-21.489-46.999-48-46.999z"></path></symbol>
    </defs>
  </svg>
</body>

</html>