

<!doctype html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Bootstrap 4 Admin &amp; Dashboard Template">
	<meta name="author" content="Bootlab">
	<link rel="icon" href="favicon.ico">

	<title>BlastMe Admin Page | Transaction Report</title>
	
	<script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
	
	<link href="../css/app.css" rel="stylesheet">
</head>
<body>
	
	<div class="splash active">
		<div class="splash-icon"></div>
	</div>

	<nav class="navbar navbar-expand navbar-dark bg-dark">
		<div class="container">
			<a class="navbar-brand" href="index.php">
				<img src="../assets/test.png" alt="NeuAPIX" class="img-fluid" width="200" height="200"/><br>
      		</a>

			<div class="navbar-collapse collapse">
				<ul class="navbar-nav ml-auto">
					<li class="nav-item dropdown ml-lg-2">
						<a class="nav-link dropdown-toggle" href="#" id="userDropdown" data-toggle="dropdown">
							<span class="d-none d-lg-inline-block">User</span>
							<span class="d-lg-none"><i class="align-middle fas fa-cog"></i></span>
            			</a>
						<div class="dropdown-menu dropdown-menu-right" aria-labelledby="userDropdown">
							<a class="dropdown-item" href="../index.php"><i class="align-middle mr-1 fas fa-fw fa-arrow-alt-circle-right"></i> Sign out</a>
						</div>
					</li>
				</ul>
			</div>
		</div>
	</nav>
	
	<div class="header">
		<div class="container">
			<div class="media text-white">
				<div class="media-body">
					<span class=" font-weight-normal">(JUDUL)</span>
				</div>
			</div>
		</div>
	</div>


	<main class="content">
		<div class="container">
			<div class="row">
				<div class="col-12 col-md-4 col-lg-3 col-xl-2">
    <a class="card d-block d-md-none mt-4" data-toggle="collapse" data-target="#sidebar">
        <div class="card-header">
            <h5 class="card-title mb-0">Menu</h5>
        </div>
    </a>

    <nav id="sidebar" class="collapse collapse-disabled-md sidebar sidebar-sticky">
        <div class="card">
            <div class="card-header">
                <h5 class="card-title mb-0">Transaction</h5>
            </div>
            <div class="sidebar-content">
                <a href="../dashboard.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c" class="sidebar-item">
                    <i class="align-middle mr-1 fas fa-fw fa-home"></i> <span class="align-middle">Dashboard</span>
                </a>
                <a class="sidebar-item" href="#transaction" data-toggle="collapse">
                    <i class="align-middle mr-1 fas fa-fw fa-desktop"></i> <span class="align-middle">Transaction</span>
                </a>
                <div class="sidebar-dropdown collapse" id="transaction" data-parent="#sidebar">
                    <a class="sidebar-item" href="./SMSTransactionReport.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c" >Transaction Report</a>
                </div>
                <div class="sidebar-dropdown collapse" id="transaction" data-parent="#sidebar">
                    <a class="sidebar-item" href="./CSVTransactionReports.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c" >Generated CSV Report</a>
                </div>
            </div>
        </div>

        
        
        
        	<div class="card">		<div class="card-header">			<h5 class="card-title mb-0">Sending</h5>		</div>		<div class="sidebar-content">			<a class="sidebar-item" href="#sendingsms" data-toggle="collapse">			<i class="align-middle mr-1 fas fa-fw fa-desktop"></i> <span class="align-middle">Sending SMS</span>			</a>			<div class="sidebar-dropdown collapse" id="sendingsms" data-parent="#sidebar">				<a class="sidebar-item" href="./AutoGeneratedANumberSMS.php?j=1c4467b8308a55dc1dce7ce9e1e3df82f833321c">Auto Generated A Number</a>			</div>		</div>	</div>

        
        
        
    </nav>
</div>

				<div class="col-12 col-md-8 col-lg-9 col-xl-10 pl-lg-4">
					<div class="row">
						<div class="col-12">
							<div class="card">
								<div class="card-header">
									<h5 class="card-title mb-0">Transaction Report - Parameter</h5>
								</div>
								<div class="card-body">
									<form>
										<div class="form-group">
											<div class="row">
												<label class="control-label col-sm-4">Transaction Date Time</label>
												<div class="col-sm-8">
													<input class="form-control" type="text" id="trxdate" name="trxdate" />
												</div>
											</div>
										</div>
									
										<div class="form-group">
											<div class="row">
												<label class="control-label col-sm-4">Client</label>
												<div class="col-sm-8">
													<select class="form-control" id="trxclient" name="trxclient">
														<option value="T0321010409146" selected>THK-MaiCi 03</option>													</select>
												</div>
											</div>
										</div>
									
										<div class="form-group">
											<div class="row">
												<label class="control-label col-sm-4">Search Field</label>
												<div class="col-sm-8">
													<select class="form-control" id="trxsearchparameter" name="trxsearchparameter">
														<option value="messageId" selected>Message ID</option>
														<option value="batchId">Batch ID</option>
														<option value="senderId">Sender ID</option>				
														<option value="destination">Destination</option>				
													</select>
												</div>
											</div>
										</div>
									
										<div class="form-group">
											<div class="row">
												<label class="control-label col-sm-4">Search Keyword</label>
												<div class="col-sm-8">
													<input class="form-control" type="text" id="trxsearchkeyword" name="trxsearchkeyword" />
												</div>
											</div>
										</div>
										
										<div class="form-group">
											<div class="row">
												<div class="col-sm-12" align="right">
													<button class="btn btn-primary" id="btnExportToCSV" name="btnExportToCSV">Export to CSV</button>&nbsp;
													<button class="btn btn-primary" id="btnViewTransaction" name="btnViewTransaction">View Report</button>&nbsp;
												</div>
											</div>
										</div>
										
									</form>									
								</div>
							</div>
						</div>
					</div>
					
					<div class="row">
						<div class="col-12">
							<div class="card">
								<div class="card-header">
									<h5 class="card-title mb-0">Transaction Report - Report</h5>
								</div>
								<div class="card-body">
									<br/><br/>
									<div id="reportpart">
										<p align="center">- no parameter defined -</p>
									</div>									
								</div>
							</div>
						</div>
					</div>					
				</div>
			</div>
		</div>
	</main>
	
	<script>
		$(function() {
  			$('input[name="trxdate"]').daterangepicker({
    			opens: 'left'
  			}, function(start, end, label) {
    			//console.log("A new date selection was made: " + start.format('YYYY-MM-DD') + ' to ' + end.format('YYYY-MM-DD'));
  			});
		});		
	</script>
	
	<script>
		$(document).ready(function(){
			doTrigger();
			
			$('#btnViewTransaction').click(function(e){
				var trxDateRange = $('#trxdate').val();
				var trxClientId = $('#trxclient').val();
				var trxSearchParameter = $('#trxsearchparameter').val();
				var trxSearchKeyword = $('#trxsearchkeyword').val();
								
				console.log(trxDateRange + ' - ' + trxClientId + ' - ' + trxSearchParameter + ' - ' + trxSearchKeyword);
				
				e.preventDefault();
				
				$.post('SMSTransactionReportDetail.php', { clientId: trxClientId, rangeDate: trxDateRange, searchParameter: trxSearchParameter, searchKeyword: trxSearchKeyword, jck: '1c4467b8308a55dc1dce7ce9e1e3df82f833321c' }, function(data){
					if(data!=null){
						if(data.startsWith('rld')){
							window.parent.location.reload();
						} else {
							$('#reportpart').css("font-size", 12);
							$('#reportpart').html(data);
						}
					} else {
						$('#reportpart').css("font-size", 12);
						$('#reportpart').html('<p>- no data found -</p>');
					};
				}).fail(function(xhr) {
					//console.log(xhr.status);
					window.parent.location.reload();
				});
			});
			
			$('#btnExportToCSV').click(function(e){
				e.preventDefault();
				
				$.post("../lib/ReportManagement.php",
				{
					parStartDate: $('#trxdate').val().split('-')[0].trim(),
					parEndDate: $('#trxdate').val().split('-')[1].trim(),
					parSearchKeyword: $('#trxsearchkeyword').val(),
					parSearchParameter: $('#trxsearchparameter').val(),
					parClientId: $('#trxclient').val(),
					parUserName: 'ThkM41Ci03',

					jck: '1c4467b8308a55dc1dce7ce9e1e3df82f833321c',
					op: "trxRpt"
					},
				function(data, status){
					console.log(data);
					if(data == "0"){
						alert("Report is being generated. You can download it later in menu \"Transaction - Generate CSV SMS Reports\".");
					} else {
						alert("Failed to generate report.");
					}
				});			

			});
		})
		
		function doTrigger(){
			var element = document.getElementById('trxclient');
			var evt = document.createEvent('HTMLEvents');
			evt.initEvent('change', false, true);
			element.dispatchEvent(evt);
		}
		
	</script>
	
		<footer class="footer">
		<div class="container">
			<hr />
			<div class="text-muted">
				<div class="row text-center justify-content-center align-self-center align-items-end">
						Provided  By &nbsp;<a href="https://www.telin.net/neuapix"><img src="../assets/test.png" alt="NeuAPIX" class="img-fluid" width="100" height="40"/></a>						
				</div>
			</div>
		</div>
	</footer>
	
	<script src="../js/app.js"></script>

	<svg width="0" height="0" style="position:absolute">
    <defs>
      <symbol viewBox="0 0 512 512" id="ion-ios-pulse-strong"><path d="M448 273.001c-21.27 0-39.296 13.999-45.596 32.999h-38.857l-28.361-85.417a15.999 15.999 0 0 0-15.183-10.956c-.112 0-.224 0-.335.004a15.997 15.997 0 0 0-15.049 11.588l-44.484 155.262-52.353-314.108C206.535 54.893 200.333 48 192 48s-13.693 5.776-15.525 13.135L115.496 306H16v31.999h112c7.348 0 13.75-5.003 15.525-12.134l45.368-182.177 51.324 307.94c1.229 7.377 7.397 11.92 14.864 12.344.308.018.614.028.919.028 7.097 0 13.406-3.701 15.381-10.594l49.744-173.617 15.689 47.252A16.001 16.001 0 0 0 352 337.999h51.108C409.973 355.999 427.477 369 448 369c26.511 0 48-22.492 48-49 0-26.509-21.489-46.999-48-46.999z"></path></symbol>
    </defs>
  </svg>
				
</body>
</html>